### ISSUE TITLE
New Host: `riscv64`

### ISSUE THREAD

**Issue by Azathothas** [pkgforge/soarpkgs#198]
Being discussed primarily: [discord](https://discord.com/channels/1313385177703256064/1379355364197404682)

### Docker Images
> Currently being built using qemu
- [alpine-builder](https://github.com/pkgforge/devscripts/pkgs/container/devscripts%2Falpine-builder/versions) (Completed)
- [debian-builder](https://github.com/pkgforge/devscripts/pkgs/container/devscripts%2Fdebian-builder-unstable) (Completed)
- [ubuntu-builder](https://github.com/pkgforge/devscripts/pkgs/container/devscripts%2Fubuntu-builder) (Completed)

### Languages

- rust
rustup doesn't work : https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/rustup/APKBUILD#L8
Alternative is using only cargo

### Package Providers
- [ppkg](https://github.com/leleliu008/ppkg) (fully-supported)
- [nix](https://github.com/NixOS/nixpkgs) (mostly-supported)
- [ix](https://github.com/stal-ix/ix) (Partially supported)
> - https://github.com/stal-ix/ix/issues/737

**Comment by Kreijstal** [comment]
I believe this will make riscv way more accessible and this repo usage will skyrocket as there are not many packages for riscv :)

**Comment by Kreijstal** [comment]
```
user@starfive:~$ ./.cargo/bin/soar list
Fetching metadata from https://meta.pkgforge.dev/bincache/riscv64-Linux.sdb.zstd
[bincache] Repository synced
[ERROR] Failed to fetch from remote source: https://meta.pkgforge.dev/pkgcache/riscv64-Linux.sdb.zstd [404 Not Found]
[ERROR] SQLite database error: no such table: shard1.packages
```

**Comment by Azathothas** [comment]
due to a lack of proper ci, `pkgcache` repo is completely missing, `bincache` is limited
Instead, I created an entire new repo `pkgforge-cargo`, which will have rust packages compiled daily, 

Currently, `"${HOME}/.config/soar/config.toml"` should look like this

```toml
#SNIPPED#

# List of configured repositories.
#
# Defines a remote repository that provides packages.
[[repositories]]
# Unique name of the repository.
name = "bincache"
# URL to the repository's metadata file.
url = "https://meta.pkgforge.dev/bincache/riscv64-Linux.sdb.zstd"
# Enables desktop integration for packages from this repository.
# Default: false
desktop_integration = false
# URL to the repository's public key (for signature verification).
pubkey = "https://meta.pkgforge.dev/bincache/minisign.pub"
# Whether the repository is enabled.
# Default: true
enabled = true
# Enables signature verification for this repository.
# Default is derived based on the existence of `pubkey`
signature_verification = true
# Optional sync interval (e.g., "1h", "12h", "1d").
# Default: "3h"
sync_interval = "3h"

[[repositories]]
name = "pkgforge-cargo"
url = "https://meta.pkgforge.dev/external/pkgforge-cargo/riscv64-Linux.json.zstd"
desktop_integration = false
signature_verification = false
sync_interval = "3h"
```
